export const TRIP_TYPE_UPDATE = "TRIP_TYPE_UPDATE"

export const PERSONS_UPDATE = "PERSONS_UPDATE"
export const  SEAT_TYPE_UPDATE = "SEAT_TYPE_UPDATE"

export const  MULTI_TRIP_FROM_TO_UPDATE = "MULTI_TRIP_FROM_TO_UPDATE"
export const  ONE_WAY_TRIP_FROM_TO_UPDATE = "ONE_WAY_TRIP_FROM_TO_UPDATE"
export const  ROUND_TRIP_FROM_TO_UPDATE = "ROUND_TRIP_FROM_TO_UPDATE"

export const  PASSENGER_DETAILS = "PASSENGER_DETAILS"

export const  PAYMENT_DETAILS = "PAYMENT_DETAILS"

export const  DIRECT_FLIGHT_UPDATE = "DIRECT_FLIGHT_UPDATE"
export const  BAGGAGE_UPDATE = "BAGGAGE_UPDATE"

export const  MORE_CITY_ADD = "MORE_CITY_ADD"
export const  MORE_CITY_REMOVE = "MORE_CITY_REMOVE"

export const  REVERSE_MULTI_CITY = "REVERSE_MULTI_CITY"
export const  REVERSE_ONE_WAY = "REVERSE_ONE_WAY"
export const  REVERSE_RETURN_CITY = "REVERSE_RETURN_CITY"


export const  ONE_WAY_DATE_UPDATE = "ONE_WAY_DATE_UPDATE"
export const  ROUND_TRIP_DATE_UPDATE = "ROUND_TRIP_DATE_UPDATE"
export const  MULTI_WAY_DATE_UPDATE = "MULTI_WAY_DATE_UPDATE"

export const  ONE_WAY_SEARCH_UPDATE = "ONE_WAY_SEARCH_UPDATE"
export const  ROUND_TRIP_SEARCH_UPDATE = "ROUND_TRIP_SEARCH_UPDATE"
export const  MULTI_WAY_SEARCH_UPDATE = "MULTI_WAY_SEARCH_UPDATE"

export const  FLIGHT_SEARCH_DATA = "FLIGHT_SEARCH_DATA"

export const  FLIGHT_OFFER_BOOKED_ID = "FLIGHT_OFFER_BOOKED_ID"
export const  FLIGHT_SELECECTED_OFFERID = "FLIGHT_SELECECTED_OFFERID"
export const  FLIGHT_SELECETED_PASSENGES = "FLIGHT_SELECETED_PASSENGES"
export const  FLIGHT_PAYMENT = "FLIGHT_PAYMENT"
export const  FLIGHT_SERVICE_UPDATE = "FLIGHT_SERVICE_UPDATE"
export const  SET_SEARCH_FROM_COOKIES = "SET_SEARCH_FROM_COOKIES"





